spring.application.name=app
spring.datasource.url=jdbc:postgresql://airplanedb_user:9YiWeUxWqB63npgz9Js8FQdgSXV8x2bw@dpg-cum9mr1u0jms73bm7bmg-a/airplanedb
spring.datasource.username=airplanedb_user
spring.datasource.password=9YiWeUxWqB63npgz9Js8FQdgSXV8x2bw
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.com.Airplane.AirplaneApp=DEBUG
logging.level.org.springframework=INFO
spring.main.allow-bean-definition-overriding=true
jwt.secret=mZGfzK7Xt+H9NfqU4yHqRqNjxPcYd/NfRzG69sZXDhs=

# Swagger/OpenAPI Properties
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=false
springdoc.packages-to-scan=com.Airplane.AirplaneApp